version: '3.6'

# services:
#   influxdb:
#     image: influxdb:1.8
#     volumes:
#       - influxdb-volume:/var/lib/influxdb
#     networks:
#       app-network:
#         ipv4_address: 172.25.2.1

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
    networks:
      app-network:
        ipv4_address: 172.25.2.1

volumes:
  mongodb-volume:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.2.0/16"
